init_checkpoint_path: weights/dit.safetensors
checkpoint_dir: finetunes/my_mochi_lora
train_data_dir: videos_prepared
attention_mode: sdpa
single_video_mode: false # Useful for debugging whether your model can learn a single video

# You only need this if you're using wandb
wandb:
project: mochi_1_lora
name: ${checkpoint_dir}
group: null

optimizer:
  lr: 2e-4
  weight_decay: 0.01

model:
  type: lora
  kwargs:
    # Apply LoRA to the QKV projection and the output projection of the attention block.
    qkv_proj_lora_rank: 16
    qkv_proj_lora_alpha: 16
    qkv_proj_lora_dropout: 0.
    qkv_proj_lora_mask: [true, true, true]
    out_proj_lora_rank: 16
    out_proj_lora_alpha: 16
    out_proj_lora_dropout: 0.

training:
  model_dtype: bf16
  warmup_steps: 200
  num_qkv_checkpoint: 48
  num_ff_checkpoint: 48
  num_post_attn_checkpoint: 48
  num_steps: 2000
  save_interval: 200
  caption_dropout: 0.1
  grad_clip: 0.0
  save_safetensors: true

# Used for generating samples during training to monitor progress ...
sample:
   interval: 200
   output_dir: ${checkpoint_dir}/samples
   decoder_path: weights/decoder.safetensors
   prompts:
       - A black and white cartoon-style scene featuring a character named st34mb04t, an anthropomorphic steamboat. st34mb04t is dancing joyfully, with its smokestacks and paddles moving rhythmically in an exaggerated, rubber-hose style reminiscent of classic 1920s animations.
       - st34mb04t steering a steamboat across choppy waters, its smokestacks bouncing and its paddles moving energetically. The scene is filled with lively, exaggerated motion in vintage black and white cartoon style.
       - st34mb04t attempting to play a trombone while tap dancing, creating a chaotic and comical scene. The smokestacks are animated like arms, waving along with the music, giving it a lively, old-time cartoon feel.
       - A humorous scene where st34mb04t is engaged in a playful chase with a fish that keeps jumping out of the water. The fish teases st34mb04t, leading to exaggerated movements and cartoonish antics.
       - st34mb04t breakdancing on the deck, spinning around on one paddlewheel while the smokestacks sway rhythmically. The scene is dynamic, packed with playful energy and the charm of classic black and white cartoons.
   seed: 12345
   kwargs:
     height: 480
     width: 848
     num_frames: 37
     num_inference_steps: 64
     sigma_schedule_python_code: linear_quadratic_schedule(64, 0.025)
     cfg_schedule_python_code: "[6.0] * 64"
