init_checkpoint_path: weights/dit.safetensors
checkpoint_dir: finetunes/my_mochi_lora
train_data_dir: videos_prepared
attention_mode: sdpa
single_video_mode: false # Useful for debugging whether your model can learn a single video

# You only need this if you're using wandb
wandb:
  # project: mochi_1_lora
  # name: ${checkpoint_dir}
  # group: null

optimizer:
  lr: 2e-4
  weight_decay: 0.01

model:
  type: lora
  kwargs:
    # Apply LoRA to the QKV projection and the output projection of the attention block.
    qkv_proj_lora_rank: 16
    qkv_proj_lora_alpha: 16
    qkv_proj_lora_dropout: 0.
    qkv_proj_lora_mask: [true, true, true]
    out_proj_lora_rank: 16
    out_proj_lora_alpha: 16
    out_proj_lora_dropout: 0.

training:
  model_dtype: bf16
  warmup_steps: 200
  num_qkv_checkpoint: 48
  num_ff_checkpoint: 48
  num_post_attn_checkpoint: 48
  num_steps: 2000
  save_interval: 200
  caption_dropout: 0.1
  grad_clip: 0.0
  save_safetensors: true

# Used for generating samples during training to monitor progress ...
sample:
   interval: 200
   output_dir: ${checkpoint_dir}/samples
   decoder_path: weights/decoder.safetensors
   prompts:
       - sl1m, wearing a white doctor's coat, dances around an office. The scene is playful, with exaggerated movements capturing the joy and freedom of sl1m's dance. The office is depicted in a cartoonish and lively style.
       - sl1m stands on a desk and performs an energetic tap dance, his white doctor's coat flaring out with every movement. The office is filled with papers fluttering, adding to the dynamic motion.
       - sl1m moonwalks across the office floor, his doctor's coat swaying back and forth. The black and white tiled floor gives a vintage vibe, and sl1m's exaggerated expressions are full of humor.
       - sl1m is doing the robot dance next to a file cabinet, his movements stiff yet comically precise. The office is bathed in warm lighting, and sl1m's antics add a fun twist to the usual setting.
       - sl1m breakdances on the office floor, spinning on his back while his white doctor's coat flares dramatically. The scene is cartoonish, full of exaggerated energy and joyful chaos.
       - sl1m, holding a stethoscope, does a playful ballet twirl in the middle of the office, his coat flowing gracefully. The scene is whimsical and lighthearted.
   seed: 12345
   kwargs:
     height: 480
     width: 848
     num_frames: 37
     num_inference_steps: 64
     sigma_schedule_python_code: "linear_quadratic_schedule(64, 0.025)"
     cfg_schedule_python_code: "[6.0] * 64"
